---
grails:
    config:
        locations:
            - ~/.grails/wekb2-config.groovy
    profile: web
    codegen:
        defaultPackage: wekb
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 50000000
            maxRequestSize: 50000000
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none

---
environments:
    development:
        dataSource:
            dbCreate: none # update // none because of database migration
            url: jdbc:postgresql://pghost:5432/wekb_dev
            username: username
            password: password
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
            pooled: true
            properties:
                maxActive: 100
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 1800000
                numTestsPerEvictionRun: 3
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                validationQuery: select 1
                defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
        grails:
            logging:
                plugin:
                    springsecurity:
                        debug:
                            useFilter: true
            mail:
                port: 3025
        cache:
            headers:
                enabled: false
        wekb:
            defaultCuratoryGroup: Local
        logging:
            config: 'grails-app/conf/logback-development.xml'
    test:
        dataSource:
            dbCreate: none # create-drop // none because of database migration
            url: jdbc:postgresql://pghost:5432/wekb_test
            username: username
            password: password
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
            pooled: true
            properties:
                maxActive: 100
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 1800000
                numTestsPerEvictionRun: 3
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                validationQuery: select 1
                defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
        grails:
            mail:
                port: 3025
        quartz:
            pluginEnabled: false
        cache:
            headers:
                enabled: false
        javamelody:
            disabled: false
    production:
        dataSource:
            dbCreate: none #update // none because of database migration
            url: jdbc:postgresql://localhost:5432/wekb_dev
            username: username
            password: password
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
            pooled: true
            properties:
                maxActive: 100
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 1800000
                numTestsPerEvictionRun: 3
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                validationQuery: select 1
                defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
